//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/apple/MyClientRemote/j2objc/CocoaPodsTest/CocoaPodsTest/JavaSource/src/SLB/Hello.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "SL/Hello.h"
#include "java/io/PrintStream.h"
#include "java/lang/Integer.h"
#include "java/lang/System.h"
#include "java/util/Stack.h"

@interface SLHello () {
 @public
  NSString *address_;
  JavaLangInteger *age_;
}

@end

J2OBJC_FIELD_SETTER(SLHello, address_, NSString *)
J2OBJC_FIELD_SETTER(SLHello, age_, JavaLangInteger *)

inline JavaUtilStack *SLHello_get_stringStack(void);
inline JavaUtilStack *SLHello_set_stringStack(JavaUtilStack *value);
static JavaUtilStack *SLHello_stringStack;
J2OBJC_STATIC_FIELD_OBJ(SLHello, stringStack, JavaUtilStack *)

@implementation SLHello

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  SLHello_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (NSString *)getNickName {
  return SLHello_getNickName();
}

- (NSString *)getAddress {
  return address_;
}

- (void)setAddressWithNSString:(NSString *)address {
  JreStrongAssign(&self->address_, address);
}

- (JavaLangInteger *)getAge {
  return age_;
}

- (void)setAgeWithJavaLangInteger:(JavaLangInteger *)age {
  JreStrongAssign(&self->age_, age);
}

+ (void)mainWithNSStringArray:(IOSObjectArray *)args {
  SLHello_mainWithNSStringArray_(args);
}

- (void)dealloc {
  RELEASE_(aaaaaaaaaaaaa_);
  RELEASE_(address_);
  RELEASE_(age_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 4, 5, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getNickName);
  methods[2].selector = @selector(getAddress);
  methods[3].selector = @selector(setAddressWithNSString:);
  methods[4].selector = @selector(getAge);
  methods[5].selector = @selector(setAgeWithJavaLangInteger:);
  methods[6].selector = @selector(mainWithNSStringArray:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "aaaaaaaaaaaaa_", "LNSString;", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "address_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "age_", "LJavaLangInteger;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "stringStack", "LJavaUtilStack;", .constantValue.asLong = 0, 0xa, -1, 6, 7, -1 },
  };
  static const void *ptrTable[] = { "setAddress", "LNSString;", "setAge", "LJavaLangInteger;", "main", "[LNSString;", &SLHello_stringStack, "Ljava/util/Stack<Ljava/lang/String;>;" };
  static const J2ObjcClassInfo _SLHello = { "Hello", "SL", ptrTable, methods, fields, 7, 0x1, 7, 4, -1, -1, -1, -1, -1 };
  return &_SLHello;
}

@end

void SLHello_init(SLHello *self) {
  NSObject_init(self);
  JreStrongAssign(&self->aaaaaaaaaaaaa_, @"123123");
  JreStrongAssign(&self->address_, @"anhui");
  JreStrongAssign(&self->age_, JavaLangInteger_valueOfWithInt_(12));
}

SLHello *new_SLHello_init() {
  J2OBJC_NEW_IMPL(SLHello, init)
}

SLHello *create_SLHello_init() {
  J2OBJC_CREATE_IMPL(SLHello, init)
}

NSString *SLHello_getNickName() {
  SLHello_initialize();
  return @"alexluan";
}

void SLHello_mainWithNSStringArray_(IOSObjectArray *args) {
  SLHello_initialize();
  JreStrongAssignAndConsume(&SLHello_stringStack, new_JavaUtilStack_init());
  [SLHello_stringStack pushWithId:@"1"];
  [((JavaUtilStack *) nil_chk(SLHello_stringStack)) pushWithId:@"2"];
  [((JavaUtilStack *) nil_chk(SLHello_stringStack)) pushWithId:@"3"];
  [((JavaUtilStack *) nil_chk(SLHello_stringStack)) pushWithId:@"4"];
  [((JavaUtilStack *) nil_chk(SLHello_stringStack)) pushWithId:@"5"];
  [((JavaUtilStack *) nil_chk(SLHello_stringStack)) pushWithId:@"6"];
  [((JavaUtilStack *) nil_chk(SLHello_stringStack)) pushWithId:@"7"];
  [((JavaUtilStack *) nil_chk(SLHello_stringStack)) removeWithId:@"3"];
  [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printWithNSString:[((JavaUtilStack *) nil_chk(SLHello_stringStack)) lastElement]];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SLHello)
