//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/apple/MyClientRemote/j2objc/CocoaPodsTest/CocoaPodsTest/JavaSource/src/Hello.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Hello")
#ifdef RESTRICT_Hello
#define INCLUDE_ALL_Hello 0
#else
#define INCLUDE_ALL_Hello 1
#endif
#undef RESTRICT_Hello

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (Hello_) && (INCLUDE_ALL_Hello || defined(INCLUDE_Hello))
#define Hello_

@class IOSObjectArray;
@class JavaLangInteger;

@interface Hello : NSObject {
 @public
  NSString *aaaaaaaaaaaaa_;
}

#pragma mark Public

- (instancetype __nonnull)init;

- (NSString *)getAddress;

- (JavaLangInteger *)getAge;

+ (NSString *)getNickName;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

- (void)setAddressWithNSString:(NSString *)address;

- (void)setAgeWithJavaLangInteger:(JavaLangInteger *)age;

@end

J2OBJC_EMPTY_STATIC_INIT(Hello)

J2OBJC_FIELD_SETTER(Hello, aaaaaaaaaaaaa_, NSString *)

FOUNDATION_EXPORT void Hello_init(Hello *self);

FOUNDATION_EXPORT Hello *new_Hello_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT Hello *create_Hello_init(void);

FOUNDATION_EXPORT NSString *Hello_getNickName(void);

FOUNDATION_EXPORT void Hello_mainWithNSStringArray_(IOSObjectArray *args);

J2OBJC_TYPE_LITERAL_HEADER(Hello)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_Hello")
